# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = E:\Programs\CMake\bin\cmake.exe

# The command to remove a file.
RM = E:\Programs\CMake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "F:\Wouter\Mijn documenten\MC\Tools\MCEdit-Unified-master\MCEdit-Unified\MCWorldLibrary\leveldb_mcpe\leveldb-mcpe"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "F:\Wouter\Mijn documenten\MC\Tools\MCEdit-Unified-master\MCEdit-Unified\MCWorldLibrary\leveldb_mcpe\leveldb-mcpe"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	E:\Programs\CMake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	E:\Programs\CMake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "F:\Wouter\Mijn documenten\MC\Tools\MCEdit-Unified-master\MCEdit-Unified\MCWorldLibrary\leveldb_mcpe\leveldb-mcpe\CMakeFiles" "F:\Wouter\Mijn documenten\MC\Tools\MCEdit-Unified-master\MCEdit-Unified\MCWorldLibrary\leveldb_mcpe\leveldb-mcpe\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "F:\Wouter\Mijn documenten\MC\Tools\MCEdit-Unified-master\MCEdit-Unified\MCWorldLibrary\leveldb_mcpe\leveldb-mcpe\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named leveldb

# Build rule for target.
leveldb: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 leveldb
.PHONY : leveldb

# fast build rule for target.
leveldb/fast:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/build
.PHONY : leveldb/fast

db/builder.obj: db/builder.cc.obj

.PHONY : db/builder.obj

# target to build an object file
db/builder.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/builder.cc.obj
.PHONY : db/builder.cc.obj

db/builder.i: db/builder.cc.i

.PHONY : db/builder.i

# target to preprocess a source file
db/builder.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/builder.cc.i
.PHONY : db/builder.cc.i

db/builder.s: db/builder.cc.s

.PHONY : db/builder.s

# target to generate assembly for a file
db/builder.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/builder.cc.s
.PHONY : db/builder.cc.s

db/c.obj: db/c.cc.obj

.PHONY : db/c.obj

# target to build an object file
db/c.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/c.cc.obj
.PHONY : db/c.cc.obj

db/c.i: db/c.cc.i

.PHONY : db/c.i

# target to preprocess a source file
db/c.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/c.cc.i
.PHONY : db/c.cc.i

db/c.s: db/c.cc.s

.PHONY : db/c.s

# target to generate assembly for a file
db/c.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/c.cc.s
.PHONY : db/c.cc.s

db/db_impl.obj: db/db_impl.cc.obj

.PHONY : db/db_impl.obj

# target to build an object file
db/db_impl.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/db_impl.cc.obj
.PHONY : db/db_impl.cc.obj

db/db_impl.i: db/db_impl.cc.i

.PHONY : db/db_impl.i

# target to preprocess a source file
db/db_impl.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/db_impl.cc.i
.PHONY : db/db_impl.cc.i

db/db_impl.s: db/db_impl.cc.s

.PHONY : db/db_impl.s

# target to generate assembly for a file
db/db_impl.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/db_impl.cc.s
.PHONY : db/db_impl.cc.s

db/db_iter.obj: db/db_iter.cc.obj

.PHONY : db/db_iter.obj

# target to build an object file
db/db_iter.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/db_iter.cc.obj
.PHONY : db/db_iter.cc.obj

db/db_iter.i: db/db_iter.cc.i

.PHONY : db/db_iter.i

# target to preprocess a source file
db/db_iter.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/db_iter.cc.i
.PHONY : db/db_iter.cc.i

db/db_iter.s: db/db_iter.cc.s

.PHONY : db/db_iter.s

# target to generate assembly for a file
db/db_iter.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/db_iter.cc.s
.PHONY : db/db_iter.cc.s

db/dbformat.obj: db/dbformat.cc.obj

.PHONY : db/dbformat.obj

# target to build an object file
db/dbformat.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/dbformat.cc.obj
.PHONY : db/dbformat.cc.obj

db/dbformat.i: db/dbformat.cc.i

.PHONY : db/dbformat.i

# target to preprocess a source file
db/dbformat.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/dbformat.cc.i
.PHONY : db/dbformat.cc.i

db/dbformat.s: db/dbformat.cc.s

.PHONY : db/dbformat.s

# target to generate assembly for a file
db/dbformat.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/dbformat.cc.s
.PHONY : db/dbformat.cc.s

db/dumpfile.obj: db/dumpfile.cc.obj

.PHONY : db/dumpfile.obj

# target to build an object file
db/dumpfile.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/dumpfile.cc.obj
.PHONY : db/dumpfile.cc.obj

db/dumpfile.i: db/dumpfile.cc.i

.PHONY : db/dumpfile.i

# target to preprocess a source file
db/dumpfile.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/dumpfile.cc.i
.PHONY : db/dumpfile.cc.i

db/dumpfile.s: db/dumpfile.cc.s

.PHONY : db/dumpfile.s

# target to generate assembly for a file
db/dumpfile.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/dumpfile.cc.s
.PHONY : db/dumpfile.cc.s

db/filename.obj: db/filename.cc.obj

.PHONY : db/filename.obj

# target to build an object file
db/filename.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/filename.cc.obj
.PHONY : db/filename.cc.obj

db/filename.i: db/filename.cc.i

.PHONY : db/filename.i

# target to preprocess a source file
db/filename.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/filename.cc.i
.PHONY : db/filename.cc.i

db/filename.s: db/filename.cc.s

.PHONY : db/filename.s

# target to generate assembly for a file
db/filename.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/filename.cc.s
.PHONY : db/filename.cc.s

db/leveldb_main.obj: db/leveldb_main.cc.obj

.PHONY : db/leveldb_main.obj

# target to build an object file
db/leveldb_main.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/leveldb_main.cc.obj
.PHONY : db/leveldb_main.cc.obj

db/leveldb_main.i: db/leveldb_main.cc.i

.PHONY : db/leveldb_main.i

# target to preprocess a source file
db/leveldb_main.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/leveldb_main.cc.i
.PHONY : db/leveldb_main.cc.i

db/leveldb_main.s: db/leveldb_main.cc.s

.PHONY : db/leveldb_main.s

# target to generate assembly for a file
db/leveldb_main.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/leveldb_main.cc.s
.PHONY : db/leveldb_main.cc.s

db/log_reader.obj: db/log_reader.cc.obj

.PHONY : db/log_reader.obj

# target to build an object file
db/log_reader.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/log_reader.cc.obj
.PHONY : db/log_reader.cc.obj

db/log_reader.i: db/log_reader.cc.i

.PHONY : db/log_reader.i

# target to preprocess a source file
db/log_reader.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/log_reader.cc.i
.PHONY : db/log_reader.cc.i

db/log_reader.s: db/log_reader.cc.s

.PHONY : db/log_reader.s

# target to generate assembly for a file
db/log_reader.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/log_reader.cc.s
.PHONY : db/log_reader.cc.s

db/log_writer.obj: db/log_writer.cc.obj

.PHONY : db/log_writer.obj

# target to build an object file
db/log_writer.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/log_writer.cc.obj
.PHONY : db/log_writer.cc.obj

db/log_writer.i: db/log_writer.cc.i

.PHONY : db/log_writer.i

# target to preprocess a source file
db/log_writer.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/log_writer.cc.i
.PHONY : db/log_writer.cc.i

db/log_writer.s: db/log_writer.cc.s

.PHONY : db/log_writer.s

# target to generate assembly for a file
db/log_writer.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/log_writer.cc.s
.PHONY : db/log_writer.cc.s

db/memtable.obj: db/memtable.cc.obj

.PHONY : db/memtable.obj

# target to build an object file
db/memtable.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/memtable.cc.obj
.PHONY : db/memtable.cc.obj

db/memtable.i: db/memtable.cc.i

.PHONY : db/memtable.i

# target to preprocess a source file
db/memtable.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/memtable.cc.i
.PHONY : db/memtable.cc.i

db/memtable.s: db/memtable.cc.s

.PHONY : db/memtable.s

# target to generate assembly for a file
db/memtable.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/memtable.cc.s
.PHONY : db/memtable.cc.s

db/repair.obj: db/repair.cc.obj

.PHONY : db/repair.obj

# target to build an object file
db/repair.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/repair.cc.obj
.PHONY : db/repair.cc.obj

db/repair.i: db/repair.cc.i

.PHONY : db/repair.i

# target to preprocess a source file
db/repair.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/repair.cc.i
.PHONY : db/repair.cc.i

db/repair.s: db/repair.cc.s

.PHONY : db/repair.s

# target to generate assembly for a file
db/repair.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/repair.cc.s
.PHONY : db/repair.cc.s

db/snappy_compressor.obj: db/snappy_compressor.cc.obj

.PHONY : db/snappy_compressor.obj

# target to build an object file
db/snappy_compressor.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/snappy_compressor.cc.obj
.PHONY : db/snappy_compressor.cc.obj

db/snappy_compressor.i: db/snappy_compressor.cc.i

.PHONY : db/snappy_compressor.i

# target to preprocess a source file
db/snappy_compressor.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/snappy_compressor.cc.i
.PHONY : db/snappy_compressor.cc.i

db/snappy_compressor.s: db/snappy_compressor.cc.s

.PHONY : db/snappy_compressor.s

# target to generate assembly for a file
db/snappy_compressor.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/snappy_compressor.cc.s
.PHONY : db/snappy_compressor.cc.s

db/table_cache.obj: db/table_cache.cc.obj

.PHONY : db/table_cache.obj

# target to build an object file
db/table_cache.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/table_cache.cc.obj
.PHONY : db/table_cache.cc.obj

db/table_cache.i: db/table_cache.cc.i

.PHONY : db/table_cache.i

# target to preprocess a source file
db/table_cache.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/table_cache.cc.i
.PHONY : db/table_cache.cc.i

db/table_cache.s: db/table_cache.cc.s

.PHONY : db/table_cache.s

# target to generate assembly for a file
db/table_cache.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/table_cache.cc.s
.PHONY : db/table_cache.cc.s

db/version_edit.obj: db/version_edit.cc.obj

.PHONY : db/version_edit.obj

# target to build an object file
db/version_edit.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/version_edit.cc.obj
.PHONY : db/version_edit.cc.obj

db/version_edit.i: db/version_edit.cc.i

.PHONY : db/version_edit.i

# target to preprocess a source file
db/version_edit.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/version_edit.cc.i
.PHONY : db/version_edit.cc.i

db/version_edit.s: db/version_edit.cc.s

.PHONY : db/version_edit.s

# target to generate assembly for a file
db/version_edit.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/version_edit.cc.s
.PHONY : db/version_edit.cc.s

db/version_set.obj: db/version_set.cc.obj

.PHONY : db/version_set.obj

# target to build an object file
db/version_set.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/version_set.cc.obj
.PHONY : db/version_set.cc.obj

db/version_set.i: db/version_set.cc.i

.PHONY : db/version_set.i

# target to preprocess a source file
db/version_set.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/version_set.cc.i
.PHONY : db/version_set.cc.i

db/version_set.s: db/version_set.cc.s

.PHONY : db/version_set.s

# target to generate assembly for a file
db/version_set.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/version_set.cc.s
.PHONY : db/version_set.cc.s

db/write_batch.obj: db/write_batch.cc.obj

.PHONY : db/write_batch.obj

# target to build an object file
db/write_batch.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/write_batch.cc.obj
.PHONY : db/write_batch.cc.obj

db/write_batch.i: db/write_batch.cc.i

.PHONY : db/write_batch.i

# target to preprocess a source file
db/write_batch.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/write_batch.cc.i
.PHONY : db/write_batch.cc.i

db/write_batch.s: db/write_batch.cc.s

.PHONY : db/write_batch.s

# target to generate assembly for a file
db/write_batch.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/write_batch.cc.s
.PHONY : db/write_batch.cc.s

db/zlib_compressor.obj: db/zlib_compressor.cc.obj

.PHONY : db/zlib_compressor.obj

# target to build an object file
db/zlib_compressor.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/zlib_compressor.cc.obj
.PHONY : db/zlib_compressor.cc.obj

db/zlib_compressor.i: db/zlib_compressor.cc.i

.PHONY : db/zlib_compressor.i

# target to preprocess a source file
db/zlib_compressor.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/zlib_compressor.cc.i
.PHONY : db/zlib_compressor.cc.i

db/zlib_compressor.s: db/zlib_compressor.cc.s

.PHONY : db/zlib_compressor.s

# target to generate assembly for a file
db/zlib_compressor.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/db/zlib_compressor.cc.s
.PHONY : db/zlib_compressor.cc.s

helpers/memenv/memenv.obj: helpers/memenv/memenv.cc.obj

.PHONY : helpers/memenv/memenv.obj

# target to build an object file
helpers/memenv/memenv.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/helpers/memenv/memenv.cc.obj
.PHONY : helpers/memenv/memenv.cc.obj

helpers/memenv/memenv.i: helpers/memenv/memenv.cc.i

.PHONY : helpers/memenv/memenv.i

# target to preprocess a source file
helpers/memenv/memenv.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/helpers/memenv/memenv.cc.i
.PHONY : helpers/memenv/memenv.cc.i

helpers/memenv/memenv.s: helpers/memenv/memenv.cc.s

.PHONY : helpers/memenv/memenv.s

# target to generate assembly for a file
helpers/memenv/memenv.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/helpers/memenv/memenv.cc.s
.PHONY : helpers/memenv/memenv.cc.s

port/port_win.obj: port/port_win.cc.obj

.PHONY : port/port_win.obj

# target to build an object file
port/port_win.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/port/port_win.cc.obj
.PHONY : port/port_win.cc.obj

port/port_win.i: port/port_win.cc.i

.PHONY : port/port_win.i

# target to preprocess a source file
port/port_win.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/port/port_win.cc.i
.PHONY : port/port_win.cc.i

port/port_win.s: port/port_win.cc.s

.PHONY : port/port_win.s

# target to generate assembly for a file
port/port_win.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/port/port_win.cc.s
.PHONY : port/port_win.cc.s

table/block.obj: table/block.cc.obj

.PHONY : table/block.obj

# target to build an object file
table/block.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/block.cc.obj
.PHONY : table/block.cc.obj

table/block.i: table/block.cc.i

.PHONY : table/block.i

# target to preprocess a source file
table/block.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/block.cc.i
.PHONY : table/block.cc.i

table/block.s: table/block.cc.s

.PHONY : table/block.s

# target to generate assembly for a file
table/block.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/block.cc.s
.PHONY : table/block.cc.s

table/block_builder.obj: table/block_builder.cc.obj

.PHONY : table/block_builder.obj

# target to build an object file
table/block_builder.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/block_builder.cc.obj
.PHONY : table/block_builder.cc.obj

table/block_builder.i: table/block_builder.cc.i

.PHONY : table/block_builder.i

# target to preprocess a source file
table/block_builder.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/block_builder.cc.i
.PHONY : table/block_builder.cc.i

table/block_builder.s: table/block_builder.cc.s

.PHONY : table/block_builder.s

# target to generate assembly for a file
table/block_builder.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/block_builder.cc.s
.PHONY : table/block_builder.cc.s

table/filter_block.obj: table/filter_block.cc.obj

.PHONY : table/filter_block.obj

# target to build an object file
table/filter_block.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/filter_block.cc.obj
.PHONY : table/filter_block.cc.obj

table/filter_block.i: table/filter_block.cc.i

.PHONY : table/filter_block.i

# target to preprocess a source file
table/filter_block.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/filter_block.cc.i
.PHONY : table/filter_block.cc.i

table/filter_block.s: table/filter_block.cc.s

.PHONY : table/filter_block.s

# target to generate assembly for a file
table/filter_block.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/filter_block.cc.s
.PHONY : table/filter_block.cc.s

table/format.obj: table/format.cc.obj

.PHONY : table/format.obj

# target to build an object file
table/format.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/format.cc.obj
.PHONY : table/format.cc.obj

table/format.i: table/format.cc.i

.PHONY : table/format.i

# target to preprocess a source file
table/format.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/format.cc.i
.PHONY : table/format.cc.i

table/format.s: table/format.cc.s

.PHONY : table/format.s

# target to generate assembly for a file
table/format.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/format.cc.s
.PHONY : table/format.cc.s

table/iterator.obj: table/iterator.cc.obj

.PHONY : table/iterator.obj

# target to build an object file
table/iterator.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/iterator.cc.obj
.PHONY : table/iterator.cc.obj

table/iterator.i: table/iterator.cc.i

.PHONY : table/iterator.i

# target to preprocess a source file
table/iterator.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/iterator.cc.i
.PHONY : table/iterator.cc.i

table/iterator.s: table/iterator.cc.s

.PHONY : table/iterator.s

# target to generate assembly for a file
table/iterator.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/iterator.cc.s
.PHONY : table/iterator.cc.s

table/merger.obj: table/merger.cc.obj

.PHONY : table/merger.obj

# target to build an object file
table/merger.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/merger.cc.obj
.PHONY : table/merger.cc.obj

table/merger.i: table/merger.cc.i

.PHONY : table/merger.i

# target to preprocess a source file
table/merger.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/merger.cc.i
.PHONY : table/merger.cc.i

table/merger.s: table/merger.cc.s

.PHONY : table/merger.s

# target to generate assembly for a file
table/merger.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/merger.cc.s
.PHONY : table/merger.cc.s

table/table.obj: table/table.cc.obj

.PHONY : table/table.obj

# target to build an object file
table/table.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/table.cc.obj
.PHONY : table/table.cc.obj

table/table.i: table/table.cc.i

.PHONY : table/table.i

# target to preprocess a source file
table/table.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/table.cc.i
.PHONY : table/table.cc.i

table/table.s: table/table.cc.s

.PHONY : table/table.s

# target to generate assembly for a file
table/table.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/table.cc.s
.PHONY : table/table.cc.s

table/table_builder.obj: table/table_builder.cc.obj

.PHONY : table/table_builder.obj

# target to build an object file
table/table_builder.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/table_builder.cc.obj
.PHONY : table/table_builder.cc.obj

table/table_builder.i: table/table_builder.cc.i

.PHONY : table/table_builder.i

# target to preprocess a source file
table/table_builder.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/table_builder.cc.i
.PHONY : table/table_builder.cc.i

table/table_builder.s: table/table_builder.cc.s

.PHONY : table/table_builder.s

# target to generate assembly for a file
table/table_builder.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/table_builder.cc.s
.PHONY : table/table_builder.cc.s

table/two_level_iterator.obj: table/two_level_iterator.cc.obj

.PHONY : table/two_level_iterator.obj

# target to build an object file
table/two_level_iterator.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/two_level_iterator.cc.obj
.PHONY : table/two_level_iterator.cc.obj

table/two_level_iterator.i: table/two_level_iterator.cc.i

.PHONY : table/two_level_iterator.i

# target to preprocess a source file
table/two_level_iterator.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/two_level_iterator.cc.i
.PHONY : table/two_level_iterator.cc.i

table/two_level_iterator.s: table/two_level_iterator.cc.s

.PHONY : table/two_level_iterator.s

# target to generate assembly for a file
table/two_level_iterator.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/table/two_level_iterator.cc.s
.PHONY : table/two_level_iterator.cc.s

util/arena.obj: util/arena.cc.obj

.PHONY : util/arena.obj

# target to build an object file
util/arena.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/arena.cc.obj
.PHONY : util/arena.cc.obj

util/arena.i: util/arena.cc.i

.PHONY : util/arena.i

# target to preprocess a source file
util/arena.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/arena.cc.i
.PHONY : util/arena.cc.i

util/arena.s: util/arena.cc.s

.PHONY : util/arena.s

# target to generate assembly for a file
util/arena.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/arena.cc.s
.PHONY : util/arena.cc.s

util/bloom.obj: util/bloom.cc.obj

.PHONY : util/bloom.obj

# target to build an object file
util/bloom.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/bloom.cc.obj
.PHONY : util/bloom.cc.obj

util/bloom.i: util/bloom.cc.i

.PHONY : util/bloom.i

# target to preprocess a source file
util/bloom.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/bloom.cc.i
.PHONY : util/bloom.cc.i

util/bloom.s: util/bloom.cc.s

.PHONY : util/bloom.s

# target to generate assembly for a file
util/bloom.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/bloom.cc.s
.PHONY : util/bloom.cc.s

util/cache.obj: util/cache.cc.obj

.PHONY : util/cache.obj

# target to build an object file
util/cache.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/cache.cc.obj
.PHONY : util/cache.cc.obj

util/cache.i: util/cache.cc.i

.PHONY : util/cache.i

# target to preprocess a source file
util/cache.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/cache.cc.i
.PHONY : util/cache.cc.i

util/cache.s: util/cache.cc.s

.PHONY : util/cache.s

# target to generate assembly for a file
util/cache.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/cache.cc.s
.PHONY : util/cache.cc.s

util/coding.obj: util/coding.cc.obj

.PHONY : util/coding.obj

# target to build an object file
util/coding.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/coding.cc.obj
.PHONY : util/coding.cc.obj

util/coding.i: util/coding.cc.i

.PHONY : util/coding.i

# target to preprocess a source file
util/coding.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/coding.cc.i
.PHONY : util/coding.cc.i

util/coding.s: util/coding.cc.s

.PHONY : util/coding.s

# target to generate assembly for a file
util/coding.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/coding.cc.s
.PHONY : util/coding.cc.s

util/comparator.obj: util/comparator.cc.obj

.PHONY : util/comparator.obj

# target to build an object file
util/comparator.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/comparator.cc.obj
.PHONY : util/comparator.cc.obj

util/comparator.i: util/comparator.cc.i

.PHONY : util/comparator.i

# target to preprocess a source file
util/comparator.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/comparator.cc.i
.PHONY : util/comparator.cc.i

util/comparator.s: util/comparator.cc.s

.PHONY : util/comparator.s

# target to generate assembly for a file
util/comparator.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/comparator.cc.s
.PHONY : util/comparator.cc.s

util/crc32c.obj: util/crc32c.cc.obj

.PHONY : util/crc32c.obj

# target to build an object file
util/crc32c.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/crc32c.cc.obj
.PHONY : util/crc32c.cc.obj

util/crc32c.i: util/crc32c.cc.i

.PHONY : util/crc32c.i

# target to preprocess a source file
util/crc32c.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/crc32c.cc.i
.PHONY : util/crc32c.cc.i

util/crc32c.s: util/crc32c.cc.s

.PHONY : util/crc32c.s

# target to generate assembly for a file
util/crc32c.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/crc32c.cc.s
.PHONY : util/crc32c.cc.s

util/env.obj: util/env.cc.obj

.PHONY : util/env.obj

# target to build an object file
util/env.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/env.cc.obj
.PHONY : util/env.cc.obj

util/env.i: util/env.cc.i

.PHONY : util/env.i

# target to preprocess a source file
util/env.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/env.cc.i
.PHONY : util/env.cc.i

util/env.s: util/env.cc.s

.PHONY : util/env.s

# target to generate assembly for a file
util/env.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/env.cc.s
.PHONY : util/env.cc.s

util/env_win.obj: util/env_win.cc.obj

.PHONY : util/env_win.obj

# target to build an object file
util/env_win.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/env_win.cc.obj
.PHONY : util/env_win.cc.obj

util/env_win.i: util/env_win.cc.i

.PHONY : util/env_win.i

# target to preprocess a source file
util/env_win.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/env_win.cc.i
.PHONY : util/env_win.cc.i

util/env_win.s: util/env_win.cc.s

.PHONY : util/env_win.s

# target to generate assembly for a file
util/env_win.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/env_win.cc.s
.PHONY : util/env_win.cc.s

util/filter_policy.obj: util/filter_policy.cc.obj

.PHONY : util/filter_policy.obj

# target to build an object file
util/filter_policy.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/filter_policy.cc.obj
.PHONY : util/filter_policy.cc.obj

util/filter_policy.i: util/filter_policy.cc.i

.PHONY : util/filter_policy.i

# target to preprocess a source file
util/filter_policy.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/filter_policy.cc.i
.PHONY : util/filter_policy.cc.i

util/filter_policy.s: util/filter_policy.cc.s

.PHONY : util/filter_policy.s

# target to generate assembly for a file
util/filter_policy.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/filter_policy.cc.s
.PHONY : util/filter_policy.cc.s

util/hash.obj: util/hash.cc.obj

.PHONY : util/hash.obj

# target to build an object file
util/hash.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/hash.cc.obj
.PHONY : util/hash.cc.obj

util/hash.i: util/hash.cc.i

.PHONY : util/hash.i

# target to preprocess a source file
util/hash.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/hash.cc.i
.PHONY : util/hash.cc.i

util/hash.s: util/hash.cc.s

.PHONY : util/hash.s

# target to generate assembly for a file
util/hash.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/hash.cc.s
.PHONY : util/hash.cc.s

util/histogram.obj: util/histogram.cc.obj

.PHONY : util/histogram.obj

# target to build an object file
util/histogram.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/histogram.cc.obj
.PHONY : util/histogram.cc.obj

util/histogram.i: util/histogram.cc.i

.PHONY : util/histogram.i

# target to preprocess a source file
util/histogram.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/histogram.cc.i
.PHONY : util/histogram.cc.i

util/histogram.s: util/histogram.cc.s

.PHONY : util/histogram.s

# target to generate assembly for a file
util/histogram.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/histogram.cc.s
.PHONY : util/histogram.cc.s

util/logging.obj: util/logging.cc.obj

.PHONY : util/logging.obj

# target to build an object file
util/logging.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/logging.cc.obj
.PHONY : util/logging.cc.obj

util/logging.i: util/logging.cc.i

.PHONY : util/logging.i

# target to preprocess a source file
util/logging.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/logging.cc.i
.PHONY : util/logging.cc.i

util/logging.s: util/logging.cc.s

.PHONY : util/logging.s

# target to generate assembly for a file
util/logging.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/logging.cc.s
.PHONY : util/logging.cc.s

util/options.obj: util/options.cc.obj

.PHONY : util/options.obj

# target to build an object file
util/options.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/options.cc.obj
.PHONY : util/options.cc.obj

util/options.i: util/options.cc.i

.PHONY : util/options.i

# target to preprocess a source file
util/options.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/options.cc.i
.PHONY : util/options.cc.i

util/options.s: util/options.cc.s

.PHONY : util/options.s

# target to generate assembly for a file
util/options.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/options.cc.s
.PHONY : util/options.cc.s

util/status.obj: util/status.cc.obj

.PHONY : util/status.obj

# target to build an object file
util/status.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/status.cc.obj
.PHONY : util/status.cc.obj

util/status.i: util/status.cc.i

.PHONY : util/status.i

# target to preprocess a source file
util/status.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/status.cc.i
.PHONY : util/status.cc.i

util/status.s: util/status.cc.s

.PHONY : util/status.s

# target to generate assembly for a file
util/status.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/status.cc.s
.PHONY : util/status.cc.s

util/testharness.obj: util/testharness.cc.obj

.PHONY : util/testharness.obj

# target to build an object file
util/testharness.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/testharness.cc.obj
.PHONY : util/testharness.cc.obj

util/testharness.i: util/testharness.cc.i

.PHONY : util/testharness.i

# target to preprocess a source file
util/testharness.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/testharness.cc.i
.PHONY : util/testharness.cc.i

util/testharness.s: util/testharness.cc.s

.PHONY : util/testharness.s

# target to generate assembly for a file
util/testharness.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/testharness.cc.s
.PHONY : util/testharness.cc.s

util/testutil.obj: util/testutil.cc.obj

.PHONY : util/testutil.obj

# target to build an object file
util/testutil.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/testutil.cc.obj
.PHONY : util/testutil.cc.obj

util/testutil.i: util/testutil.cc.i

.PHONY : util/testutil.i

# target to preprocess a source file
util/testutil.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/testutil.cc.i
.PHONY : util/testutil.cc.i

util/testutil.s: util/testutil.cc.s

.PHONY : util/testutil.s

# target to generate assembly for a file
util/testutil.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/testutil.cc.s
.PHONY : util/testutil.cc.s

util/win_logger.obj: util/win_logger.cc.obj

.PHONY : util/win_logger.obj

# target to build an object file
util/win_logger.cc.obj:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/win_logger.cc.obj
.PHONY : util/win_logger.cc.obj

util/win_logger.i: util/win_logger.cc.i

.PHONY : util/win_logger.i

# target to preprocess a source file
util/win_logger.cc.i:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/win_logger.cc.i
.PHONY : util/win_logger.cc.i

util/win_logger.s: util/win_logger.cc.s

.PHONY : util/win_logger.s

# target to generate assembly for a file
util/win_logger.cc.s:
	$(MAKE) -f CMakeFiles\leveldb.dir\build.make CMakeFiles/leveldb.dir/util/win_logger.cc.s
.PHONY : util/win_logger.cc.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... leveldb
	@echo ... db/builder.obj
	@echo ... db/builder.i
	@echo ... db/builder.s
	@echo ... db/c.obj
	@echo ... db/c.i
	@echo ... db/c.s
	@echo ... db/db_impl.obj
	@echo ... db/db_impl.i
	@echo ... db/db_impl.s
	@echo ... db/db_iter.obj
	@echo ... db/db_iter.i
	@echo ... db/db_iter.s
	@echo ... db/dbformat.obj
	@echo ... db/dbformat.i
	@echo ... db/dbformat.s
	@echo ... db/dumpfile.obj
	@echo ... db/dumpfile.i
	@echo ... db/dumpfile.s
	@echo ... db/filename.obj
	@echo ... db/filename.i
	@echo ... db/filename.s
	@echo ... db/leveldb_main.obj
	@echo ... db/leveldb_main.i
	@echo ... db/leveldb_main.s
	@echo ... db/log_reader.obj
	@echo ... db/log_reader.i
	@echo ... db/log_reader.s
	@echo ... db/log_writer.obj
	@echo ... db/log_writer.i
	@echo ... db/log_writer.s
	@echo ... db/memtable.obj
	@echo ... db/memtable.i
	@echo ... db/memtable.s
	@echo ... db/repair.obj
	@echo ... db/repair.i
	@echo ... db/repair.s
	@echo ... db/snappy_compressor.obj
	@echo ... db/snappy_compressor.i
	@echo ... db/snappy_compressor.s
	@echo ... db/table_cache.obj
	@echo ... db/table_cache.i
	@echo ... db/table_cache.s
	@echo ... db/version_edit.obj
	@echo ... db/version_edit.i
	@echo ... db/version_edit.s
	@echo ... db/version_set.obj
	@echo ... db/version_set.i
	@echo ... db/version_set.s
	@echo ... db/write_batch.obj
	@echo ... db/write_batch.i
	@echo ... db/write_batch.s
	@echo ... db/zlib_compressor.obj
	@echo ... db/zlib_compressor.i
	@echo ... db/zlib_compressor.s
	@echo ... helpers/memenv/memenv.obj
	@echo ... helpers/memenv/memenv.i
	@echo ... helpers/memenv/memenv.s
	@echo ... port/port_win.obj
	@echo ... port/port_win.i
	@echo ... port/port_win.s
	@echo ... table/block.obj
	@echo ... table/block.i
	@echo ... table/block.s
	@echo ... table/block_builder.obj
	@echo ... table/block_builder.i
	@echo ... table/block_builder.s
	@echo ... table/filter_block.obj
	@echo ... table/filter_block.i
	@echo ... table/filter_block.s
	@echo ... table/format.obj
	@echo ... table/format.i
	@echo ... table/format.s
	@echo ... table/iterator.obj
	@echo ... table/iterator.i
	@echo ... table/iterator.s
	@echo ... table/merger.obj
	@echo ... table/merger.i
	@echo ... table/merger.s
	@echo ... table/table.obj
	@echo ... table/table.i
	@echo ... table/table.s
	@echo ... table/table_builder.obj
	@echo ... table/table_builder.i
	@echo ... table/table_builder.s
	@echo ... table/two_level_iterator.obj
	@echo ... table/two_level_iterator.i
	@echo ... table/two_level_iterator.s
	@echo ... util/arena.obj
	@echo ... util/arena.i
	@echo ... util/arena.s
	@echo ... util/bloom.obj
	@echo ... util/bloom.i
	@echo ... util/bloom.s
	@echo ... util/cache.obj
	@echo ... util/cache.i
	@echo ... util/cache.s
	@echo ... util/coding.obj
	@echo ... util/coding.i
	@echo ... util/coding.s
	@echo ... util/comparator.obj
	@echo ... util/comparator.i
	@echo ... util/comparator.s
	@echo ... util/crc32c.obj
	@echo ... util/crc32c.i
	@echo ... util/crc32c.s
	@echo ... util/env.obj
	@echo ... util/env.i
	@echo ... util/env.s
	@echo ... util/env_win.obj
	@echo ... util/env_win.i
	@echo ... util/env_win.s
	@echo ... util/filter_policy.obj
	@echo ... util/filter_policy.i
	@echo ... util/filter_policy.s
	@echo ... util/hash.obj
	@echo ... util/hash.i
	@echo ... util/hash.s
	@echo ... util/histogram.obj
	@echo ... util/histogram.i
	@echo ... util/histogram.s
	@echo ... util/logging.obj
	@echo ... util/logging.i
	@echo ... util/logging.s
	@echo ... util/options.obj
	@echo ... util/options.i
	@echo ... util/options.s
	@echo ... util/status.obj
	@echo ... util/status.i
	@echo ... util/status.s
	@echo ... util/testharness.obj
	@echo ... util/testharness.i
	@echo ... util/testharness.s
	@echo ... util/testutil.obj
	@echo ... util/testutil.i
	@echo ... util/testutil.s
	@echo ... util/win_logger.obj
	@echo ... util/win_logger.i
	@echo ... util/win_logger.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

